
name: Staging and Production Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python test_ai_features_complete.py
          python test_gps_location_complete.py
          # If you have a pytest setup, you can just run: pytest

  deploy-staging:
    name: Deploy to Staging
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }} # You'll need to add this secret
          username: ${{ secrets.STAGING_USER }} # And this one
          key: ${{ secrets.STAGING_SSH_KEY }} # And this one
          script: |
            # Assumes you have a separate project folder for staging
            cd ~/PerformanceTracker-Staging
            git pull origin develop
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart performance-tracker-staging
            echo "Staging deployment successful!"

  deploy-production:
    name: Deploy to Production
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: 
      name: production
      url: http://${{ secrets.DO_HOST }} # Optional: Link to your live site
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/PerformanceTracker
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart performance-tracker
            echo "Production deployment successful!"
